---
# tasks file for roles/netplan

# ------------------------------------------------------------------------------
- name: "NETPLAN | apt | install apt services"
  become: true
  ansible.builtin.apt:
    pkg: netplan.io
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  when:
    - netplan_install is defined
    - netplan_install | bool
  tags:
    - netplan

# ------------------------------------------------------------------------------
- name: "NETPLAN | search files to delete in {{ netplan_dir }}"
  become: true
  ansible.builtin.find:
    paths: "{{ netplan_dir }}"
    patterns: "*.yml,*yaml"
    excludes: "{{ netplan_file }}"
  register: files_to_delete
  when: netplan_remove_existing | bool
  tags:
    - netplan

- name: "NETPLAN | delete founded files in {{ netplan_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_delete.files | flatten(levels=1) }}"
  when: files_to_delete.files is defined and netplan_remove_existing | bool
  tags:
    - netplan

# ------------------------------------------------------------------------------
# - name: "copy netplan.yaml template into {{ netplan_dir }}/{{ netplan_file }}"
#   become: true
#   ansible.builtin.template:
#     src: "{{ 'netplan.yaml.j2' | from_yaml }}"
#     dest: "{{ netplan_dir }}/{{ netplan_file }}"
#     owner: root
#     group: root
#     mode: "0640"
#   register: netplan_changed_template
#   when: netplan_renderer == 'networkd'
#   tags: netplan

- name: "NETPLAN | copy netplan.yaml template into {{ netplan_dir }}/{{ netplan_file }}"
  become: true
  ansible.builtin.template:
    src: "{{ 'netplan.yaml.j2' | from_yaml }}"
    dest: "{{ netplan_dir }}/{{ netplan_file }}"
    owner: root
    group: root
    mode: "0640"
  register: netplan_changed_template
  when: netplan_configuration is defined and netplan_configuration != []
  notify: netplan generate config
  tags:
    - netplan

# ------------------------------------------------------------------------------
- name: "NETPLAN | disable and stop systemd-resolved"
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  when: netplan_renderer != 'networkd'
  tags:
    - netplan
