---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-netplan"
      ansible.builtin.include_role:
        name: "ansible-netplan"
  vars:
    netplan_install: yes
    netplan_remove_existing: yes
