---
blank_issues_enabled: false
contact_links:
  - name: 🤔 I have a question or need support
    url: https://github.com/MVladislav/ansible-netplan/discussions
    about: This issue tracker is for bugs only, not general support questions. Please refer to our Discussions.
  - name: 🚀 Feature Request
    url: https://github.com/MVladislav/ansible-netplan/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like.
  - name: 🔒 Report a Security Vulnerability
    url: https://github.com/MVladislav/ansible-netplan/security/advisories
    about: If you believe you have found a security vulnerability, please report it here.
