---
# handlers file for roles/netplan

- name: "NETPLAN | generating netplan configuration"
  become: true
  ansible.builtin.command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  register: netplan_apply
  tags:
    - netplan

- name: "NETPLAN | applying netplan configuration"
  become: true
  ansible.builtin.command: netplan apply
  listen: netplan apply config
  when:
    - netplan_apply is not defined or netplan_apply | bool
  tags:
    - netplan
