---
# handlers file for roles/netplan

- name: "NETPLAN | generating netplan configuration"
  become: true
  ansible.builtin.command: netplan generate
  changed_when: false
  failed_when: false
  listen: Netplan generate config
  notify: Netplan apply config
  register: netplan_apply
  tags:
    - netplan

- name: "NETPLAN | applying netplan configuration"
  become: true
  ansible.builtin.command: netplan apply
  changed_when: false
  failed_when: false
  listen: netplan apply config
  when:
    - netplan_apply is not defined or netplan_apply | bool
  tags:
    - netplan
